//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestEmail.MailService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InputMail", Namespace="http://schemas.datacontract.org/2004/07/MyCardSystemMail")]
    [System.SerializableAttribute()]
    public partial class InputMail : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string addressFromField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string addressNameFromField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string addressNameToField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string addressToField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string bodyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string fileNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string filebyteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string subjectField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string addressFrom {
            get {
                return this.addressFromField;
            }
            set {
                if ((object.ReferenceEquals(this.addressFromField, value) != true)) {
                    this.addressFromField = value;
                    this.RaisePropertyChanged("addressFrom");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string addressNameFrom {
            get {
                return this.addressNameFromField;
            }
            set {
                if ((object.ReferenceEquals(this.addressNameFromField, value) != true)) {
                    this.addressNameFromField = value;
                    this.RaisePropertyChanged("addressNameFrom");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string addressNameTo {
            get {
                return this.addressNameToField;
            }
            set {
                if ((object.ReferenceEquals(this.addressNameToField, value) != true)) {
                    this.addressNameToField = value;
                    this.RaisePropertyChanged("addressNameTo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string addressTo {
            get {
                return this.addressToField;
            }
            set {
                if ((object.ReferenceEquals(this.addressToField, value) != true)) {
                    this.addressToField = value;
                    this.RaisePropertyChanged("addressTo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string body {
            get {
                return this.bodyField;
            }
            set {
                if ((object.ReferenceEquals(this.bodyField, value) != true)) {
                    this.bodyField = value;
                    this.RaisePropertyChanged("body");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string fileName {
            get {
                return this.fileNameField;
            }
            set {
                if ((object.ReferenceEquals(this.fileNameField, value) != true)) {
                    this.fileNameField = value;
                    this.RaisePropertyChanged("fileName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string filebyte {
            get {
                return this.filebyteField;
            }
            set {
                if ((object.ReferenceEquals(this.filebyteField, value) != true)) {
                    this.filebyteField = value;
                    this.RaisePropertyChanged("filebyte");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string subject {
            get {
                return this.subjectField;
            }
            set {
                if ((object.ReferenceEquals(this.subjectField, value) != true)) {
                    this.subjectField = value;
                    this.RaisePropertyChanged("subject");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReturnResult", Namespace="http://schemas.datacontract.org/2004/07/MyCardSystemMail")]
    [System.SerializableAttribute()]
    public partial class ReturnResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int LogSnField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReturnMsgField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ReturnMsgNoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorCode {
            get {
                return this.ErrorCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorCodeField, value) != true)) {
                    this.ErrorCodeField = value;
                    this.RaisePropertyChanged("ErrorCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int LogSn {
            get {
                return this.LogSnField;
            }
            set {
                if ((this.LogSnField.Equals(value) != true)) {
                    this.LogSnField = value;
                    this.RaisePropertyChanged("LogSn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReturnMsg {
            get {
                return this.ReturnMsgField;
            }
            set {
                if ((object.ReferenceEquals(this.ReturnMsgField, value) != true)) {
                    this.ReturnMsgField = value;
                    this.RaisePropertyChanged("ReturnMsg");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ReturnMsgNo {
            get {
                return this.ReturnMsgNoField;
            }
            set {
                if ((this.ReturnMsgNoField.Equals(value) != true)) {
                    this.ReturnMsgNoField = value;
                    this.RaisePropertyChanged("ReturnMsgNo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MailService.IMailService")]
    public interface IMailService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMailService/Mail", ReplyAction="http://tempuri.org/IMailService/MailResponse")]
        TestEmail.MailService.ReturnResult Mail(TestEmail.MailService.InputMail Value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMailService/Mail", ReplyAction="http://tempuri.org/IMailService/MailResponse")]
        System.Threading.Tasks.Task<TestEmail.MailService.ReturnResult> MailAsync(TestEmail.MailService.InputMail Value);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMailServiceChannel : TestEmail.MailService.IMailService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MailServiceClient : System.ServiceModel.ClientBase<TestEmail.MailService.IMailService>, TestEmail.MailService.IMailService {
        
        public MailServiceClient() {
        }
        
        public MailServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MailServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MailServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MailServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public TestEmail.MailService.ReturnResult Mail(TestEmail.MailService.InputMail Value) {
            return base.Channel.Mail(Value);
        }
        
        public System.Threading.Tasks.Task<TestEmail.MailService.ReturnResult> MailAsync(TestEmail.MailService.InputMail Value) {
            return base.Channel.MailAsync(Value);
        }
    }
}
